#项目名
name: lh-ui-react

# 只有在main分支发生push事件时触发
on:
  push:
    branches:
      - master

# 工作流
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境

    steps:
      # 拉代码
      - name: Checkout code
        uses: actions/checkout@v1

      # 下载node，我这里指定了15.x，这个版本可随意，高于dumi规定的node版本即可
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # 打包代码
      - name: Build Project
        run: |
          npm install      
          npm run docs:build

      # 部署到github
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: build # 打包的内容放到build分支下
          folder: docs-dist # 你打包后存放的文件
          ACCESS_TOKEN: ${{secrets.LHUIBUILD}}

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - run: |
          git config --global user.name "lh"
          git config --global user.email "2731164534@qq.com"
          npm install
          npm version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
